[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "arkitect==0.2.1",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "volcengine>=1.0.183",
]