news:
  - key: "sina-stock-homepage"
    name: "新浪-股票首页"
    url: "https://finance.sina.com.cn/stock/"
    crop: true
  - key: "sina-public-company-news"
    name: "新浪-上市公司新闻"
    url: "https://finance.sina.com.cn/roll/index.d.html?cid=56592&page=1"
  - key: "sina-market-news"
    name: "新浪-大盘新闻"
    url: "https://finance.sina.com.cn/roll/index.d.html?cid=56589&page=1"
  - key: "csj-financial-headlines"
    name: "中国证券报-财经要闻"
    url: "https://www.cs.com.cn/xwzx/hg/"
  - key: "csj-company_news"
    name: "中国证券报-公司新闻"
    url: "https://www.cs.com.cn/ssgs/"
  - key: "csj-jinniuzuo"
    name: "中国证券报-中证金牛座-实时新闻"
    url: "https://jnz.cs.com.cn/app/jnz/list"
  # - key: "csj-homepage"
  #   name: "中国证券报-首页"
  #   url: "https://www.cs.com.cn/"
  #   crop: true
  - key: "0033-homepage"
    name: "同花顺-首页"
    url: "https://www.10jqka.com.cn/"
    crop: true
  - key: "0033-finacial-news"
    name: "同花顺-财经要闻"
    url: "https://news.10jqka.com.cn/today_list/"
  - key: "0033-macroeconomy-news"
    name: "同花顺-宏观经济新闻"
    url: "https://news.10jqka.com.cn/cjzx_list/"
money:
  # - key: "sina-individual-A-shares-increase-ranking"
  #   name: "新浪-个股（A股）涨幅排名"
  #   url: "https://vip.stock.finance.sina.com.cn/mkt/#stock_hs_up"
  # - key: "sina-individual-A-shares-decrease-ranking"
  #   name: "新浪-个股（A股）跌幅排名"
  #   url: "https://vip.stock.finance.sina.com.cn/mkt/#stock_hs_down"
  - key: "sina-sector-increase"
    name: "新浪-股票板块涨跌幅"
    url: "https://finance.sina.com.cn/stock/sl/"
  # - key: "0033-individual-A-shares-increase-ranking"
  #   name: "同花顺-个股（A股）行情"
  #   url: "https://q.10jqka.com.cn/"
  - key: "sohu-individual-A-shares-5d-increase-ranking"
    name: "搜狐五日涨幅排行榜"
    url: "https://q.stock.sohu.com/cn/jdph/jdph_shenshi_5d_00.shtml"
  - key: "sohu-individual-A-shares-3d-increase-ranking"
    name: "搜狐三日涨幅排行榜"
    url: "https://q.stock.sohu.com/cn/jdph/jdph_shenshi_3d_00.shtml"
  - key: "sohu-individual-A-shares-15d-increase-ranking"
    name: "搜狐十五日涨幅排行榜"
    url: "https://q.stock.sohu.com/cn/jdph/jdph_shenshi_15d_00.shtml"
  - key: "sohu-individual-A-shares-60d-increase-ranking"
    name: "搜狐六十日涨幅排行榜"
    url: "https://q.stock.sohu.com/cn/jdph/jdph_shenshi_60d_00.shtml"
individual_stock:
  money:
    - key: "money-sohu-individual-stock"
      name: "搜狐-个股近期数据"
      url: "https://q.stock.sohu.com/cn/{}/lshq.shtml"
      # url: "https://q.stock.sohu.com/cn/000983/index.shtml"
  news:
    - key: "news-baidu-individual-stock"
      name: "百度-个股新闻搜索"
      url: "https://www.baidu.com/s?tn=news&rtt=1&bsst=1&wd={}&cl=2"
      # "https://www.baidu.com/s?tn=news&rtt=1&bsst=1&wd=欧菲光&cl=2"
